version: "3"
services:
  jenkins:
    image: sunhao/jenkins
    build: .
    container_name: jenkins
    restart: always
    network_mode: "bridge"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
